kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codeready-operator
subjects:
  - kind: ServiceAccount
    name: codeready-operator
    namespace: codeready
roleRef:
  kind: ClusterRole
  name: codeready-operator
  apiGroup: rbac.authorization.k8s.io